const milletData = {
    Ananthapuram: { en: 'Sorghum', enHindi: 'Jowar', hi: 'ज्वार' },
    KonaSeema: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    Anakapalli: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    'Alluri Sitharama Raju District': { en: 'Finger Millet', enHindi: 'Ragi', hi: 'रागी' },
    Bapatla: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    Chitoor: { en: 'Finger Millet', enHindi: 'Ragi', hi: 'रागी' },
    Eluru: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    Guntur: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    'Sri Satyasai District': { en: 'Finger Millet', enHindi: 'Ragi', hi: 'रागी' },
    'YSR Kadapa': { en: 'Sorghum', enHindi: 'Jowar', hi: 'ज्वार' },
    Kakinada: { en: 'Foxtail Millet', enHindi: '', hi: 'कांगनी' },
    Kurnool: { en: 'Kodo Millet', enHindi: '', hi: 'कोदो' },
    Krishna: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    Nandyal: { en: 'Sorghum', enHindi: 'Jowar', hi: 'ज्वार' },
    Palnadu: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    'West Godawari': { en: 'Foxtail Millet', enHindi: '', hi: 'कांगनी' },
    'Sri potti Sriramalu Nellore': { en: 'Finger Millet', enHindi: 'Ragi', hi: 'रागी' },
    Prakasam: { en: 'Barnyard Millet', enHindi: '', hi: 'जंगली बाजरा' },
    'Manyam District': { en: 'Finger Millet', enHindi: 'Ragi', hi: 'रागी' },
    'East Godavari': { en: 'Sorghum', enHindi: 'Jowar', hi: 'ज्वार' },
    AnnamyyaDistrict: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    Srikakulam: { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    'Sri Balaji Dist.': { en: 'Pearl Millet', enHindi: 'Bajra', hi: 'बाजरा' },
    Vizianagaram: { en: 'Finger Millet', enHindi: 'Ragi', hi: 'रागी' },
    'NTR District': { en: 'Finger Millet', enHindi: 'Ragi', hi: 'रागी' },
    Visakhapatnam: { en: 'Finger Millet', enHindi: 'Ragi', hi: 'रागी' },
};
export default milletData;